apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: profileservice
spec:
  replicas: 2
  strategy:
   type: RollingUpdate
   rollingUpdate:
      maxSurge: 1
      maxUnavailable: 24%
  selector:
    matchLabels:
      app: profileservice
  template:
    metadata:
      labels:
        app: profileservice
    spec:
      containers:
      - name: profileservice-container
        image: rcavinash123/profileservice:v1.0.1
        ports:
          - containerPort: 4003
            protocol: TCP
        resources:
          requests:
            memory: 512Mi
          limits:
            memory: 1Gi
        env:
          - name: DEBUG_MODE
            value: "0"
        readinessProbe:
          httpGet:
            path: /auth/healthz
            port: 4003
          initialDelaySeconds: 20
          periodSeconds: 20
          